import Head from "next/head";
import Card from "../components/shared/Card";
import LandingCard from "../components/shared/LandingCard";
import getAllPosts from "../services/posts/getAllPosts";

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title>Rawnaq</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <div className="mt-4">
          <LandingCard />
        </div>
        <div className="grid grid-cols-3 gap-3 p-3 ">
          {posts.map((post) => (
            <Card
              key={post._id}
              title={post.title}
              image={post.img}
              author={post.author.full_name}
              publishDate={post.createdAt}
              content={post.description}
              slug={post.slug}
            />
          ))}
        </div>
      </section>
    </div>
  );
}

export async function getStaticProps() {
  const response = await getAllPosts();
  const posts = await response.json();
  
  return {
    props: {
      posts: posts,
    },
  };
}
